version: 2.1
jobs:
  azure-acr/build-and-push-image:
    machine: true
    steps:
      - checkout
  
  deploy-staging:
    machine: true
    steps:
      - run:
          name: Deploy Over SSH
          command: |
            TAG=release.<< pipeline.number >>
            echo 'export TAG=release.<< pipeline.number >>' >> $BASH_ENV
            echo 'export ${REGISTRY_NAME}' >> $BASH_ENV
            echo 'export ${SERVER_NAME}' >> $BASH_ENV
            ssh penta@devstable.eastus.cloudapp.azure.com  " az acr login --name $REGISTRY_NAME && sudo docker pull $SERVER_NAME/ma-plugin-identify:$TAG && sudo docker run -d --name ma-plugin-identify-test  -e GATEWAY_URL=http://devstable.eastus.cloudapp.azure.com:8080 -p 50:80 --restart always $SERVER_NAME/ma-plugin-identify:$TAG"
            
  sonar:
    docker:
      - image: 'circleci/node'
    steps:
      - checkout
      - run:
          name: Install dependencies and build project
          command: npm install
      - sonarcloud/scan
orbs:
  azure-acr: circleci/azure-acr@0.2.1
executors:
  docker_build:
    machine:
      docker_layer_caching: true
workflows:
  version: 2.1
  ma-plugin-identify-staging:
    jobs:
      - deploy-staging:
          context: ACR
          requires:
            - azure-acr/staging
          filters:
            branches:
              only:
                - master   
      - azure-acr/build-and-push-image:
          name: azure-acr/staging
          context: ACR
          login-server-name: $SERVER_NAME
          registry-name: $REGISTRY_NAME
          dockerfile: Dockerfile
          executor: docker_build
          repo: ma-plugin-identify
          tag: release.<< pipeline.number >>        
          filters:
            branches:
              only:
                - master
     

